https://www.freewebmentor.com/python-programs

In [3]:
a=[]
no=int(input('enter the number of elements '))
for i in range(0,no):
    j=int(input('enter the number: '))
    a.append(j)
print(a)
print(np.mean(a))

enter the number of elements 4
enter the number: 67
enter the number: 78
enter the number: 45
enter the number: 90
[67, 78, 45, 90]
70.0


In [3]:
a=int(input('first number '))
b=int(input('second number '))
a,b=b,a
print(a)
print(b)


first number 3
second number 4
4
3


In [7]:
n=int(input('enter the number u want '))
t=str(n)
t1=t+t
t2=t+t+t
print(int(t1))
print(int(t2))
total=n+int(t1)+int(t2)
total

enter the number u want 5
55
555


615

In [1]:
n=int(input('enter the number:'))
t=str(n)
t1=t+t
t2=t+t+t
print(int(t1))
print(int(t2))
print(int(t)+(t1)+(t2))
#this wont work,

enter the number:5
55
555


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [22]:
d=0
n=int(input('enter n times u want '))
f=input('the the number ')
for i in range(1,n+1):
    c=f*i
    c=int(c)
    d=d+c
    print(c)
print(d)

enter n times u want 3
the the number 5
5
55
555
615


In [8]:
f=input('enter:')
print(f[0])
print(f[1])

enter:23
2
3


In [9]:
g=(input('number '))
print(g[::-1])

number 65743
34756


In [15]:
n=int(input("Enter number: "))
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
print("Reverse of the number:",rev)

Enter number: 645
Reverse of the number: 546


In [16]:
645%10

5

In [17]:
645//10

64

In [18]:
n=int(input('enter the number: '))
rev=0
while n>0:
    remain=n%10
    rev=rev*10+remain
    n=n//10
print('Reverse the number: ',rev)
    

enter the number: 645
Reverse the number:  546


In [20]:
sub1=int(input("Enter marks of the first subject: "))
sub2=int(input("Enter marks of the second subject: "))
sub3=int(input("Enter marks of the third subject: "))
sub4=int(input("Enter marks of the fourth subject: "))
sub5=int(input("Enter marks of the fifth subject: "))
avg=(sub1+sub2+sub3+sub4+sub4)/5
if avg>=90:
    print('Grade A')
elif avg>=80 and avg<90:
    print('Grade B')
elif avg>=70 and avg<80:
    print("Grade: C")
elif avg>=60 and avg<70:
     print("Grade: D")
else:
    print("Grade: F")


Enter marks of the first subject: 34
Enter marks of the second subject: 45
Enter marks of the third subject: 46
Enter marks of the fourth subject: 47
Enter marks of the fifth subject: 48
Grade: F


In [1]:
mark=int(input('Enter the number: '))
stud=[]
grade=[]
for i in range(1,mark+1):
    rang=int(input('enter marks: '))
    stud.append(rang)
for j in stud:
    if j>90:
        print('s grade')
        grade.append('s grade')
    elif j >=70 and j<90:
        print('A grade')
        grade.append('A grade')
    elif j >=50 and j<70:
        print('B Grade')
        grade.append('B grade')
    elif j>=30 and j<50:
        print('C Grade')
        grade.append('C grade')
    elif j< 30:
        print('Fail')
        grade.append('Fail')
    else:
        print('Invalid input')
print(stud)
print(grade)

Enter the number: 6
enter marks: 20
enter marks: 45
enter marks: 70
enter marks: 97
enter marks: 79
enter marks: 36
Fail
C Grade
A grade
s grade
A grade
C Grade
[20, 45, 70, 97, 79, 36]
['Fail', 'C grade', 'A grade', 's grade', 'A grade', 'C grade']


In [7]:
list1=[]
lower_limit=int(input('enter the number '))
higher_limit=int(input('enter the number '))
number=int(input('enter the number '))
for i in range(lower_limit,higher_limit+1):
    if (i%number==0):
        list1.append(i)
print(list1)        
    

enter the number 2
enter the number 20
enter the number 2
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [9]:
a=int(input('enter the numerator'))
b=int(input('enter the denomenator: '))
c,d=divmod(a,b)
print( 'the qoutient is ',c)
print('the remainder is ',d)

enter the numerator10
enter the denomenator: 3
the qoutient is  3
the remainder is  1


In [13]:
a=int(input('enter the number '))
b = int(input('Etner number'))
c = int(input('Etner number'))
lst=[]
lst.append(a)
lst.append(b)
lst.append(c)
print(lst)
x=[]
for i in lst:
    for j in lst:
        for k in lst:
            x.append(100*i+10*j+k)
print(set(x))

enter the number 3
Etner number5
Etner number7
[3, 5, 7]
{773, 775, 777, 533, 535, 537, 553, 555, 557, 573, 575, 577, 333, 335, 337, 733, 735, 353, 737, 355, 357, 753, 755, 373, 757, 375, 377}


In [1]:
a=int(input('enter the first number:'))
b=int(input('enter the second number:'))
c=int(input('enter the third number:'))
lst=[]
lst.extend([a,b,c])
print(lst)
x=[]
for i in lst:
    for j in lst:
        for k in lst:
            x.append(100*i+10*j+k)
print(set(x))           

enter the first number:1
enter the second number:2
enter the third number:3
[1, 2, 3]
{131, 132, 133, 311, 312, 313, 321, 322, 323, 331, 332, 333, 211, 212, 213, 221, 222, 223, 231, 232, 233, 111, 112, 113, 121, 122, 123}


In [1]:
lower=int(input('enter the lower range '))
higher=int(input('enter the higher range '))
even=[]
odd=[]
for i in range(lower,higher+1):
    if i%2==0:
        even.append(i)
    else:
        odd.append(i)
print('the even numbers are', even)
print('the odd numbers are ',odd)

enter the lower range 45
enter the higher range 56
the even numbers are [46, 48, 50, 52, 54, 56]
the odd numbers are  [45, 47, 49, 51, 53, 55]


In [2]:
lower=int(input('enter the lower range'))
higher=int(input('enter the higher range'))
odd=[]
for i in range(lower,higher+1):
    if i%2!=0:
        odd.append(i)
print(odd)

enter the lower range1
enter the higher range20
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [2]:
s=input('enter a number ')
c=0
for i in s:
    c=c+int(i)
print('the sum of digits in the number is: ',c)

enter a number 657489342
the sum of digits in the number is:  48


In [3]:
n=input('enter the number:')
c=0
for i in n:
    c+=int(i)
print(c)

enter the number:213
6


In [4]:
s=input('enter a number: ')
if s == s[::-1]:n
    
    print('palindrome')
else:
    print('not a palindrome')

enter a number: 4567
not a palindrome


In [2]:
numbers=[]
for i in range(1,51):
    if (i%2 !=0) and (i%3 !=0):
        numbers.append(i)
print('the numbers not divisible by 2 and 3 are ',numbers)

the numbers not divisible by 2 and 3 are  [1, 5, 7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49]


In [1]:
numbers=[]
for i in range(1,51):
    if (i%2 !=0) or (i%3 !=0):
        numbers.append(i)
print('the numbers not divisible by 2 and 3 are ',numbers)

the numbers not divisible by 2 and 3 are  [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 37, 38, 39, 40, 41, 43, 44, 45, 46, 47, 49, 50]


In [6]:
n=int(input('enter the number '))
a=[]
d=0
for i in range(1,n+1):
    a.append(i)
print(a)

enter the number 4
[1, 2, 3, 4]


In [4]:
n=int(input('enter the number '))
a=[]
d=0
for i in range(1,n+1):
    a.append(i)
    if i<n:
        print(i,'+',end=" ")
    else:
        print(i,'=',end=' ')
print(sum(a))


enter the number 5
1 + 2 + 3 + 4 + 5 = 15


In [11]:
n=int(input('enter the number: '))
for j in range(1,n+1):
    a=[]
    for i in range(1,j+1):
        print(i,sep=' ',end=' ')
        if (i<j):
            print('+',sep=' ',end=' ')
        a.append(i)
    print('=',sum(a))ix
    
print()
        

enter the number: 4
1 = 1
1 + 2 = 3
1 + 2 + 3 = 6
1 + 2 + 3 + 4 = 10



In [16]:
n=int(input('enter the number: '))
for i in range(0,n):
    for j in range(0,n):
        if i==j:
            print('1',sep=' ',end=' ')
        else:
            print('0',sep=' ',end=' ')
    print()
   

enter the number: 6
1 0 0 0 0 0 
0 1 0 0 0 0 
0 0 1 0 0 0 
0 0 0 1 0 0 
0 0 0 0 1 0 
0 0 0 0 0 1 


In [17]:
n=int(input('enter the number '))
for i in range(0,n):
    c=np.eye(n)
print(c)

enter the number 6
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [20]:
n=int(input('enter a number: '))
for i in range(0,n+1):
    a=[]
    for j in range(0,n+1):
        if i==j:
            a.append(1)
        else:
            a.append(0)
    print(a)

enter a number: 5
[1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 1]


In [21]:
n=int(input('enter the number of rows: '))
for i in range(n,0,-1):
    print(i*'*')

enter the number of rows: 4
****
***
**
*


In [5]:
n=int(input('enter the number of rows: '))
for i in range(0,n):
    print(i*'*')

enter the number of rows: 5

*
**
***
****


In [23]:
n=int(input('enter the number of rows: '))
for i in range(n,0,-1):
    print((n-i)*' '+i*'*')

enter the number of rows: 5
*****
 ****
  ***
   **
    *


In [24]:
n=int(input('enter the number: '))
for i in range(1,n+1):
    print('*')
    

enter the number: 5
*
*
*
*
*


# strings

In [25]:
string=input('enter a string:')
string=string.replace('a','$')
string=string.replace('A','$')
print('modified string',string)

enter a string:ahgdfhahcbha
modified string $hgdfh$hcbh$


In [26]:
def remove(string,n):
    first=string[:n]
    last=string[n+1:]
    return first+last
string=input('enter the string: ')
n=int(input('enter the index of the character to be removed '))
print('modified string',remove(string,n))

ehter the string: annonaalex
enter the index of the character to be removed 3
modified string annnaalex


In [28]:
string1=input('enter the string: ')
string2=input('enter the string ')
if (sorted(string1)==sorted(string2)):
    print('the strings are anagrams')
else:
    print('the strings are not anagrams.')


enter the string: anona
enter the string annona
the strings are not anagrams.


In [30]:
def change(string):
    return string[-1:]+string[1:-1]+string[:1]
string=input('enter the string:')
print(change(string))

enter the string:annonaalex
xnnonaalea


In [5]:
def change(string):
    return(string[-1]+string[1:-1]+string[0])
string=input('enter the string:')
print(change(string))

enter the string:annonalex
xnnonalea


In [35]:
string=input('enter the string: ')
vowels=0
for i in string:
    if(i=='a' or i=='e' or i=='i' or i=='o'or i=='u'):
        vowels=vowels+1
print('number of vowels are: ',vowels)


enter the string: annonaalex
number of vowels are:  5


In [37]:
string=input('enter the string: ')
string=string.replace(' ','-')
print('modified string',string)



enter the string: annona alex
modified string annona-alex


In [38]:
string=input('enter the string: ')
stringlength=0
for i in string:
    stringlength=stringlength+1
print(stringlength)

enter the string: annonaalex
10


In [41]:
string=input('enter the string: ')
final=''
for i in range(len(string)):
    if i%2==0:
        final=final+string[i]
print(final)

        


enter the string: annona alex
ann lx


In [42]:
string=input('enter the string: ')
char=0
word=1
for i in string:
    char=char+1
    if(i==(' ')):
        word=word+1
print('number of words in the string: ',word)
print('number of charachers in the string',char)

enter the string: annona elizabeth alias
number of words in the string:  3
number of charachers in the string 22


In [6]:
string=input('enter the string:')
word=1
char=0
for i in string:
    if i==' ':
        word=word+1
    else:
        char+=1
print(word)
print(char)

enter the string:annona alex
2
10


In [44]:
string1=input('enter the string1: ')
string2=input('enter the string2: ')
c1=0
c2=0
for i in string1:
    c1=c1+1
for i in string2:
    c2=c2+1
if c1>c2:
    print('string1 greater than string2')
elif c1==c2:
    print('both strings are equal')
else:
    print('string2 greater than string1')
    

enter the string1: annona
enter the string2: aquilin
string2 greater than string1


In [46]:
string=input('enter the string: ')
count=0
for i in string:
    if (i.islower()):
        count=count+1
print('no of lower case characters is:',count)

enter the string: Annona Alex
no of lower case characters is: 8


In [47]:
string1=input('enter the string2: ')

c1=0
c2=0
for i in string:
    if (i.islower()):
        c1=c1+1
    elif (i.isupper()):
        c2=c2+1


print('no of lower case characters is:',c1)
print('no of upper case cahracters is:',c2)


enter the string2: Annona Alex
no of lower case characters is: 8
no of upper case cahracters is: 2


In [53]:
from string import ascii_lowercase as lower_case
def check(s):
    return set(lower_case)-set(s.lower())==set([])
s=input('enter the string: ')
if(check(s)==True):
    print('the string is a pangram')
else:
    print('the string is not a pangram')


enter the string: The quick brown fox jumps over the lazy dog
the string is a pangram


In [51]:
set(lower_case)

{'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [52]:
set(s.lower())

{' ',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [56]:
hyphen_separated_words=input('enter the string:')
lst=[n for n in hyphen_separated_words.split('-')]
lst.sort()
print('sorted:')
print('-'.join(lst))
    

enter the string:Annona-Elizabeth-Alias
sorted:
Alias-Annona-Elizabeth


In [27]:
string=input('enter the string: ')
c1=0
c2=0
for i in string:
    if (i.isdigit()):
        c1=c1+1
    else:
        c2=c2+1
print('the number of digits is: ',c1)
print('the number of letters is: ',c2)

        

enter the string: annonaelza312gmailcom
the number of digits is:  3
the number of letters is:  18


In [63]:
string=input('enter the string: ')
count=0
for i in string:
    count=count+1
new_string=string[0:2]+string[count-2:count]
print('new string is :',new_string)

enter the string: annonalex
new string is : anex


In [65]:
string=input('enter the string: ')

a=[]

a=string.split(' ')
a


enter the string: annona alias aquilin alias


['annona', 'alias', 'aquilin', 'alias']

In [66]:
string=input('enter the string: ')
word=input('enter the word: ')
a=[]
count=0
a=string.split(' ')
for i in range(0,len(a)):
    if word==a[i]:
        count=count+1
print('the count of',word,'is',count)


enter the string: annona alias aquilin alias
enter the word: alias
the count of alias is 2


In [1]:
string=input('enter the string: ')
w=input('enter the word: ')
a=[]
c=0
a=string.split(' ')
for i in a:
    if w==i:
        c+=1
print(c)


enter the string: annona annona
enter the word: annona
2


In [68]:
string=input('enter the string: ')
sub_string=input('enter the string: ')
if(string.find(sub_string)==-1):
    print('substring is not found in the string')
else:
    print('substring  found in the string')

enter the string: annona alias
enter the string: alias
substring  found in the string


In [3]:
string=input('enter the string: ')
a=[]
a=string.split(' ')
sub=input('enter the substring: ')
for i in a:
    if i in sub:
        print('yes')
        break
else:
    print('no')

enter the string: annona alias
enter the substring: alias
yes


# sets

In [75]:
string=input('enter the string: ')
vowels=('a','e','1','o','u')
count=0
for i in string:
    if i in vowels:
        count +=1
print('count of vowel is:',count)


enter the string: annona
count of vowel is: 3


In [76]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
a=list(set(s1)&set(s2))
print('the common letters are:')
for i in a:
    print(i)

enter the first string: annona 
enter the second string: alias
the common letters are:
a


In [78]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
a=list(set(s1)&set(s2))
a

enter the first string: annona
enter the second string: anona


['n', 'a', 'o']

In [4]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
s1set=set(s1)
s2set=set(s2)
c=0
a=[]
for i in s1set:
    if i in s2set:
        c+=1
        a.append(i)
print(c)
print(a)
        

enter the first string: annona
enter the second string: annona
3
['a', 'o', 'n']


In [82]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
a=list(set(s1)-set(s2))
print(a)
for i in a:
    print('the letters are:',i)

enter the first string: annona
enter the second string: alex
['n', 'o']
the letters are: n
the letters are: o


In [5]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
s1set=set(s1)
s2set=set(s2)
c=0
a=[]
for i in s1set:
    if i  not in s2set:
        c+=1
        a.append(i)
print(c)
print(a)
        

enter the first string: annona
enter the second string: alex
2
['o', 'n']


In [83]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
a=list(set(s1)^set(s2))
print('the common letters are: ',a)

enter the first string: annona
enter the second string: alex
the common letters are:  ['n', 'x', 'l', 'o', 'e']


In [6]:
s1=input('enter the first string: ')
s2=input('enter the second string: ')
s1set=set(s1)
s2set=set(s2)
c=0
a=[]
for i in s1set:
    if i  not in s2set:
        c+=1
        a.append(i)
for i in s2set:
    if i  not in s1set:
        c+=1
        a.append(i)
print(c)
print(a)

enter the first string: annona
enter the second string: alex
5
['o', 'n', 'l', 'x', 'e']


# LIST

In [1]:
lst=[1,2,3,4,5,6,7,9]
print('thr largest number is',max(lst))

thr largest number is 9


In [7]:
a=[]
n=int(input('enter the number of elements in the list wanted:'))
for i in range(n):
    b=int(input('enter the number'))
    a.append(b)
print(max(a))

enter the number of elements in the list wanted:12
enter the number23
enter the number34
enter the number5
enter the number3457
enter the number34
enter the number56
enter the number34
enter the number23
enter the number123
enter the number234
enter the number567
enter the number789
3457


In [4]:
a=[]
n=int(input('enter the number of elements in the list'))
for i in range(n):
    b=int(input('enter the number added to the list: '))
    a.append(b)
a.sort()
print('largest number is: ',a[n-1])
print('largest number is: ',max(a))

enter the number of elements in the list4
enter the number added to the list: 23
enter the number added to the list: 67
enter the number added to the list: 89
enter the number added to the list: 10000
largest number is:  10000
largest number is:  10000


In [1]:
a=[]
n=int(input('enter the number : '))
for i in range(n):
    b=int(input('enter the number: '))
    a.append(b)
a.sort()
print('the second largest number is: ',a[n-2])

enter the number : 4
enter the number: 12
enter the number: 34
enter the number: 67
enter the number: 89
the second largest number is:  67


In [2]:
lst=[]
even=[]
odd=[]
n=int(input('enter the number of elements: '))
for i in range(n):
    b=int(input('enter the numbers: '))
    lst.append(i)
print(lst)
for i in lst:
    if i%2==0:
        even.append(i)
    else:
        odd.append(i)
print(even)
print(odd)
    

enter the number of elements: 8
enter the numbers: 1
enter the numbers: 2
enter the numbers: 3
enter the numbers: 4
enter the numbers: 5
enter the numbers: 6
enter the numbers: 7
enter the numbers: 8
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 2, 4, 6]
[1, 3, 5, 7]


In [5]:
a=[]
n=int(input('enter the number of elements: '))
for i in range(n):
    b=input('enter the string: ')
    a.append(b)
print(a)
a.sort(key=len)
print('the sorted list is:',a)

enter the number of elements: 3
enter the string: annona
enter the string: alex
enter the string: alias
['annona', 'alex', 'alias']
the sorted list is: ['alex', 'alias', 'annona']


In [6]:
l1 = []
num1 = int(input('Enter size of list 1: '))
for n in range(num1):
    numbers1 = int(input('Enter any number:'))
    l1.append(numbers1)
 
l2 = []
num2 = int(input('Enter size of list 2:'))
for n in range(num2):
    numbers2 = int(input('Enter any number:'))
    l2.append(numbers2)
    
union=list(set().union(l1,l2))
print('the union of the list is:',union)

Enter size of list 1: 3
Enter any number:3
Enter any number:4
Enter any number:5
Enter size of list 2:4
Enter any number:2
Enter any number:6
Enter any number:3
Enter any number:5
the union of the list is: [2, 3, 4, 5, 6]


In [7]:
l1 = []
num1 = int(input('Enter size of list 1: '))
for n in range(num1):
    numbers1 = int(input('Enter any number:'))
    l1.append(numbers1)
 
l2 = []
num2 = int(input('Enter size of list 2:'))
for n in range(num2):
    numbers2 = int(input('Enter any number:'))
    l2.append(numbers2)
inter=list(set(l1)&set(l2))
print(inter)

Enter size of list 1: 3
Enter any number:2
Enter any number:3
Enter any number:4
Enter size of list 2:3
Enter any number:4
Enter any number:3
Enter any number:5
[3, 4]


In [30]:
rangelower=int(input('enter the lower range: '))
rangeupper=int(input('enter the upper range: '))
a=[(x,x**2) for x in range(rangelower,rangeupper+1)]
print(a)

enter the lower range: 0
enter the upper range: 1
[(0, 0), (1, 1)]


In [8]:
x=1str(x)

'10'

In [7]:
x=10
a=list(map(int,str(x)))
print(a)

[1, 0]


In [10]:
l=int(input('enter the lower range: '))
u=int(input('enter the higher range: '))
x=[]
a=[x for x in range(l,u+1) if(int(x**0.5))**2==x and sum(list(map(int,str(x))))<10]
print(a)

enter the lower range: 2
enter the higher range: 20
[4, 9, 16]


In [14]:
a=[]
n=int(input('enter the number of elements in list: '))
for x in range(0,n):
    element=int(input('enter element'+str(x+1) +':'))
    a.append(element)
print(a)

enter the number of elements in list: 3
enter element1:4
enter element2:5
enter element3:6
[4, 5, 6]


In [16]:
a=[]
n=int(input('enter the number of elements in list: '))
for x in range(0,n):
    element=int(input('enter element'+str(x+1) +':'))
    a.append(element)
b=[sum(a[0:x+1]) for x in range(0,len(a))]
print('the original list:',a)
print('the new list is:',b)

enter the number of elements in list: 4
enter element1:3
enter element2:4
enter element3:5
enter element4:6
the original list: [3, 4, 5, 6]
the new list is: [3, 7, 12, 18]


In [18]:
import random

In [19]:
a=[]
n=int(input('enter the number of elements: '))
for j in range(n):
    a.append(random.randint(1,20))
print('randomised list is: ',a)

enter the number of elements: 4
randomised list is:  [3, 2, 16, 1]


In [21]:
a=input('enter the list of tuples: ')
def last(n):
    return n[-1]
def sort(m):
    return sorted(m,key=last)
print('sorted',sort(a))

enter the list of tuples: [(2,5),(3,5),(8,6),(5,3)]
sorted ['(', '(', '(', '(', ')', ')', ')', ')', ',', ',', ',', ',', ',', ',', ',', '2', '3', '3', '5', '5', '5', '6', '8', '[', ']']


In [22]:
def last(n):
    return n[-1]  
 
def sort(tuples):
    return sorted(tuples, key=last)
 
a=input("Enter a list of tuples:")
print("Sorted:")
print(sort(a))

Enter a list of tuples:[(2,5),(1,2),(4,4),(2,3)]
Sorted:
['(', '(', '(', '(', ')', ')', ')', ')', ',', ',', ',', ',', ',', ',', ',', '1', '2', '2', '2', '3', '4', '4', '5', '[', ']']


In [26]:
a=[]
n=int(input('enter the number of elements: '))
for x in range(0,n):
    element=int(input('enter the number: '))
    a.append(element)
temp=a[0]
a[0]=a[n-1]
a[n-1]=temp
print('new list: ',a)

enter the number of elements: 4
enter the number: 1
enter the number: 2
enter the number: 3
enter the number: 4
new list:  [4, 2, 3, 1]


# Python Program to Remove the Duplicate Items from a List

In [29]:
a=[]
n= int(input("Enter the number of elements in list:"))
for x in range(0,n):
    element=int(input("Enter element" + str(x+1) + ":"))
    a.append(element)
b=set()
unique=[]
for x in a:
    if x not in b:
        unique.append(x)
        b.add(x)
print('non duplicate items: ',unique)

Enter the number of elements in list:5
Enter element1:1
Enter element2:1
Enter element3:2
Enter element4:2
Enter element5:3
non duplicate items:  [1, 2, 3]


In [9]:
a=[]
n=int(input('enter the number of elements in the list'))
for i in range(n):
    m=int(input('enter the number'))
    a.append(m)
print(a)
b=[]
for i in a:
    if i not in b:
        b.append(i)
print(b)

enter the number of elements in the list7
enter the number1
enter the number2
enter the number3
enter the number2
enter the number3
enter the number4
enter the number5
[1, 2, 3, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [30]:
a=[]
n=int(input('enter the no of elements: '))
for i in range(n):
    e=input('enter the element: ')
    a.append(e)
max1=len(a[0])
temp=a[0]
for i in a:
    if(len(i)>max1):
        max1=len(i)
        temp=i
print('the word with the longestlength is',temp)

enter the no of elements: 4
enter the element: annona
enter the element: aquilin
enter the element: alias
enter the element: sherly
the word with the longestlength is aquilin


In [31]:
a=[]
n=int(input('enter the number of elements: '))
for x in range(0,n):
    element=input('enter the element: ')
    a.append(element)
print(a)
c=[]
m=0
b=input('enter the word to remove: ')
n=int(input('enter the occurence to remove: '))
for i in a:
    if(i==b):
        m=m+1
        if(m !=n):
            c.append(i)
    else:
        c.append(i)
print('the updated list is',c)
    

enter the number of elements: 6
enter the element: a
enter the element: b
enter the element: s
enter the element: a
enter the element: b
enter the element: s
['a', 'b', 's', 'a', 'b', 's']
enter the word to remove: a
enter the occurence to remove: 2
the updated list is ['a', 'b', 's', 'b', 's']


In [11]:
a=[]
n=int(input('enter the number of elements in the list: '))
for i in range(n):
    j=input('enter the word'+str(i+1)+':')
    a.append(j)
print(a)
m=input('enter the word to remove: ')
q=int(input('enter the occurence of '+ m +' to remove: '))
x=0
k=[]
for i in a:
    if i==m:
        x+=1
        if x!=q:
            k.append(i)
    else:
        k.append(i)
print(k)     

enter the number of elements in the list: 5
enter the word1:anno
enter the word2:aqu
enter the word3:anno
enter the word4:aqu
enter the word5:aqu
['anno', 'aqu', 'anno', 'aqu', 'aqu']
enter the word to remove: aqu
enter the occurence of aqu to remove: 2
['anno', 'aqu', 'anno', 'aqu']


# dictionary

In [32]:
d={}
key=int(input('enter the key value: '))
value=int(input('enter the value: '))
d.update({key:value})
print(d)         

enter the key value: 1
enter the value: 3
{1: 3}


In [34]:
d={}
n=int(input('enter the number of key value pairs: '))
for i in range(0,n):
    key=int(input('enter the key value: '))
    value=int(input('enter the value: '))
    d.update({key:value})
print(d)    

enter the number of key value pairs: 2
enter the key value: 2
enter the value: 3
enter the key value: 3
enter the value: 4
{2: 3, 3: 4}


In [35]:
d={'a':1,'b':2,'c':3}
key=input('enter the key: ')
if key in d.keys():
    print('key is present')
else:
    print('key not present')

enter the key: a
key is present


In [37]:
n=int(input('enter the number: '))
d={x:x*x for x in range(n)}
d

enter the number: 9


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [39]:
d={'A':100,'B':540,'C':239}
print("Total sum of values in the dictionary:")
print(sum(d.values()))


Total sum of values in the dictionary:
879


In [40]:
d={'A':10,'B':10,'C':239}
tot=1
for i in d:    
    tot=tot*d[i]
print(tot)

23900


In [42]:
d = {'a':1,'b':2,'c':3,'d':4}
print("Initial dictionary")
print(d)
key=input("Enter the key to delete(a-d):")
if key in d: 
    del d[key]
else:
    print("Key not found!")
    exit(0)
print("Updated dictionary")
print(d)

Initial dictionary
{'a': 1, 'b': 2, 'c': 3, 'd': 4}
Enter the key to delete(a-d):a
Updated dictionary
{'b': 2, 'c': 3, 'd': 4}


In [43]:
keys=[]
values=[]
n=int(input("Enter number of elements for dictionary:"))
print("For keys:")
for x in range(0,n):
    element=int(input("Enter element" + str(x+1) + ":"))
    keys.append(element)
print("For values:")
for x in range(0,n):
    element=int(input("Enter element" + str(x+1) + ":"))
    values.append(element)
d=dict(zip(keys,values))
print("The dictionary is:")
print(d)

Enter number of elements for dictionary:2
For keys:
Enter element1:2
Enter element2:3
For values:
Enter element1:3
Enter element2:2
The dictionary is:
{2: 3, 3: 2}


In [1]:
k=[]
v=[]
n=int(input('enter the number of key value pairs needed:'))
print('for keys:')
for i in range(n):
    key=input('enter the key: ')
    k.append(key)
    value=input('enter the value: ')
    v.append(value)
print(k)
print(v)
d=dict(zip(k,v))
d

enter the number of key value pairs needed:2
for keys:
enter the key: anno
enter the value: 1
enter the key: aqu
enter the value: 2
['anno', 'aqu']
['1', '2']


{'anno': '1', 'aqu': '2'}

In [44]:
string=input('enter a string: ')
l=[]
l=string.split()
l

enter a string: anno alias aquilin alias


['anno', 'alias', 'aquilin', 'alias']

In [45]:
string=input('enter a string: ')
l=[]
l=string.split()
wordfrq=[l.count(p) for p in l]
print(dict(zip(l,wordfrq)))

enter a string: anno alias anno aqu alias
{'anno': 2, 'alias': 2, 'aqu': 1}


# Python Programming Examples on Mathematical Functions:

w3:schools:https://www.w3resource.com/python-exercises/

# Print a list after removing specified elements

In [2]:
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
color=[x for (i,x) in enumerate(color) if i not in (0,4,5) ]
color

['Green', 'White', 'Black']

In [3]:
test_list = [[5, 6, 8], [8, 5, 3], [9, 10, 3]] 
res=[]
track=[]
count=0
for i in test_list:
    res.append([])
print(res)

[[], [], []]


In [7]:
test_list = [[5, 6, 8], [8, 5, 3], [9, 10, 3]] 
res=[]
track=[]
count=0
for i in test_list:
    res.append([])
    for ele in i:
        if ele not in track:
            res[count].append(ele)
            track.append(ele)
    count+=1
print(res)

[[5, 6, 8], [3], [9, 10]]


In [10]:
test_str = "abbabba"
res = test_str.replace('a', '%temp%').replace('b', 'a').replace('%temp%', 'b')
res

'baabaab'

In [12]:
s=input('enter the word: ')
words=[word for word in s.split(' ')]
print(' '.join(sorted(list(set(words)))))

enter the word: annona elizabeth alias
alias annona elizabeth


In [14]:
items=[]
for i in range(2000,3001):
    s=str(i)
    if (int(s[0])%2==0) and (int(s[1])%2==0) and (int(s[2])%2==0) and (int(s[3])%2==0):
        items.append((s))
print(','.join(items))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888


In [15]:
test_str = "Geeks"
  
# printing original string  
print("The original string is : " + str(test_str)) 
  
# Get all substrings of string 
# Using list comprehension + string slicing 
res = [test_str[i: j] for i in range(len(test_str)) 
          for j in range(i + 1, len(test_str) + 1)] 
  
# printing result  
print("All substrings of string are : " + str(res)) 

The original string is : Geeks
All substrings of string are : ['G', 'Ge', 'Gee', 'Geek', 'Geeks', 'e', 'ee', 'eek', 'eeks', 'e', 'ek', 'eks', 'k', 'ks', 's']


In [16]:
row_num = int(input("Input number of rows: "))
col_num = int(input("Input number of columns: "))
multi_list = [[0 for col in range(col_num)] for row in range(row_num)]

for row in range(row_num):
    for col in range(col_num):
        multi_list[row][col]= row*col

print(multi_list)

Input number of rows: 3
Input number of columns: 4
[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]


In [23]:
user_input = input("Enter values for row and column number: ")
rows, cols = user_input.split(",")
rows = int(rows)
cols = int(cols)

grid = []
for x in range(rows):
    row = []
    for y in range(cols):
        row.append(x * y)
    grid.append(row)
    print(row)

print()
print(grid)

Enter values for row and column number: 3,4
[0, 0, 0, 0]
[0, 1, 2, 3]
[0, 2, 4, 6]

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]


In [24]:
mystring = "This is programs Buzz" 
mylist = [word[0] for word in mystring.split()]
print(mylist)

['T', 'i', 'p', 'B']


In [26]:
tp = (1,2,3,4,5,6,7,8,9,10)
tp1 = tp[:5]
tp2 = tp[5:]
print(tp1)
print(tp2)

(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)


In [ ]:
python programme to generate  A 

In [3]:
lst=[12,24,35,67]
lst1=[x for x in lst if x != 24]
lst1


[12, 35, 67]

In [5]:
num = [7,8, 120, 25, 44, 20, 27]
num = [x for x in num if x%2!=0 and  x%5!=0]
print(num)

[7, 27]


In [6]:
import numpy as np

In [8]:
np.random.rand(5,5)

array([[0.72261016, 0.97498755, 0.86386783, 0.29692116, 0.97864531],
       [0.49047507, 0.12683383, 0.29514826, 0.73872111, 0.6969089 ],
       [0.62191031, 0.85770869, 0.19318855, 0.80991247, 0.12468187],
       [0.69194409, 0.88323109, 0.98562502, 0.68483374, 0.52257606],
       [0.33118895, 0.92997717, 0.36923791, 0.07411425, 0.69026643]])

In [9]:
np.random.rand(0,50,10)

array([], shape=(0, 50, 10), dtype=float64)

In [11]:

s=np.random.randint(0,50,10)
s


array([37, 23, 45,  7, 22,  7, 22, 11, 43,  3])

In [13]:
s.reshape((5, 2))


array([[37, 23],
       [45,  7],
       [22,  7],
       [22, 11],
       [43,  3]])

In [16]:
s=np.random.randint(range(10))
s

TypeError: int() argument must be a string, a bytes-like object or a number, not 'range'

In [17]:
import array as ar

In [21]:
s=ar.array
s

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
s=np.random.randint(0,10,10)
s


array([6, 8, 5, 1, 6, 3, 0, 7, 9, 5])

In [23]:
s[8]

9

In [26]:
arr = np.arange(0, 10, 2)

In [27]:
arr

array([0, 2, 4, 6, 8])

In [2]:
n=int(input("Enter an integer:"))
print("Factors are:")
i=1
while(i<=n):
    k=0
    if(n%i==0):
        j=1
        while(j<=i):
            if(i%j==0):
                k=k+1
            j=j+1
        if(k==2):
            print(i)
    i=i+1

Enter an integer:50
Factors are:
2
5


In [3]:
n=int(input("Enter an integer:"))
print("The divisors of the number are:")
for i in range(1,n+1):
    if(n%i==0):
        print(i)

Enter an integer:70
The divisors of the number are:
1
2
5
7
10
14
35
70


In [4]:
n=int(input("Enter the number to print the tables for:"))
for i in range(1,11):
    print(n,"x",i,"=",n*i)

Enter the number to print the tables for:8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


In [5]:
n=int(input("Enter the number of elements to be in the list:"))
b=[]
for i in range(0,n):
    a=int(input("Element: "))
    b.append(a)
sum1=0
sum2=0
sum3=0
for j in b:
    if(j>0):
        if(j%2==0):
            sum1=sum1+j
        else:
            sum2=sum2+j
    else:
        sum3=sum3+j
print("Sum of all positive even numbers:",sum1)
print("Sum of all positive odd numbers:",sum2)

Enter the number of elements to be in the list:5
Element: 6
Element: 8
Element: 7
Element: 7
Element: 8
Sum of all positive even numbers: 22
Sum of all positive odd numbers: 14


In [6]:
n=int(input("Enter the number of elements to be in the list:"))
b=[]
for i in range(0,n):
    a=int(input("Element: "))
    b.append(a)
sum1=0
sum2=0
sum3=0
for j in b:
    if(j>0):
        if(j%2==0):
            sum1=sum1+j
        else:
            sum2=sum2+j
    else:
        sum3=sum3+j
print("Sum of all positive even numbers:",sum1)
print("Sum of all positive odd numbers:",sum2)
print("Sum of all negative numbers:",sum3)


Enter the number of elements to be in the list:3
Element: 4
Element: 7
Element: 8
Sum of all positive even numbers: 12
Sum of all positive odd numbers: 7
Sum of all negative numbers: 0


In [7]:
n=int(input("Enter the number of elements to be in the list:"))
b=[]
for i in range(0,n):
    a=int(input("Element: "))
    b.append(a)
c=[]
d=[]
for i in b:
    if(i%2==0):
        c.append(i)
    else:
        d.append(i)
c.sort()
d.sort()
count1=0
count2=0
for k in c:
    count1=count1+1
for j in d:
    count2=count2+1
print("Largest even number:",c[count1-1])
print("Largest odd number",d[count2-1])

Enter the number of elements to be in the list:5
Element: 3
Element: 4
Element: 5
Element: 6
Element: 7
Largest even number: 6
Largest odd number 7


In [8]:
lower=int(input("Enter the lower range:"))
upper=int(input("Enter the upper range:"))
for i in range (lower,upper+1):
    if(i%7==0 and i%5==0):
        print(i)

Enter the lower range:6
Enter the upper range:90
35
70


In [9]:
n=int(input("Enter any number: "))
a=list(map(int,str(n)))
b=list(map(lambda x:x**3,a))
if(sum(b)==n):
    print("The number is an armstrong number. ")
else:
    print("The number isn't an arsmtrong number. ")

Enter any number: 9
The number isn't an arsmtrong number. 


In [10]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
if(a>b):
    min1=a
else:
    min1=b
while(1):
    if(min1%a==0 and min1%b==0):
        print("LCM is:",min1)
        break
    min1=min1+1

Enter the first number:8
Enter the second number:23
LCM is: 184


In [11]:
import math
a=int(input("Enter first side: "))
b=int(input("Enter second side: "))
c=int(input("Enter third side: "))
s=(a+b+c)/2
area=math.sqrt(s*(s-a)*(s-b)*(s-c))
print("Area of the triangle is: ",round(area,2))

Enter first side: 6
Enter second side: 7
Enter third side: 8
Area of the triangle is:  20.33


In [12]:
m1=float(input("Enter the first mass: "))
m2=float(input("Enter the second mass: "))
r=float(input("Enter the distance between the centres of the masses: "))
G=6.673*(10**-11)
f=(G*m1*m2)/(r**2)
print("Hence, the gravitational force is: ",round(f,2),"N")

Enter the first mass: 7
Enter the second mass: 8
Enter the distance between the centres of the masses: 6
Hence, the gravitational force is:  0.0 N


In [13]:
a=int(input("Enter number: "))
k=0
for i in range(2,a//2+1):
    if(a%i==0):
        k=k+1
if(k<=0):
    print("Number is prime")
else:
    print("Number isn't prime")
    

Enter number: 7
Number is prime


In [14]:
r=int(input("Enter upper limit: "))
for a in range(2,r+1):
    k=0
    for i in range(2,a//2+1):
        if(a%i==0):
            k=k+1
    if(k<=0):
        print(a)

Enter upper limit: 9
2
3
5
7


In [15]:
n=int(input("Enter a number: "))
sum1 = 0
while(n > 0):
    sum1=sum1+n
    n=n-1
print("The sum of first n natural numbers is",sum1)

Enter a number: 8
The sum of first n natural numbers is 36


In [16]:
a=[]
n=int(input("Enter number of elements:"))
for i in range(1,n+1):
    b=int(input("Enter element:"))
    a.append(b)
k=0
num=int(input("Enter the number to be counted:"))
for j in a:
    if(j==num):
        k=k+1
print("Number of times",num,"appears is",k)

Enter number of elements:7
Enter element:5
Enter element:7
Enter element:7
Enter element:8
Enter element:9
Enter element:8
Enter element:7
Enter the number to be counted:7
Number of times 7 appears is 3


In [17]:
ef is_power_of_two(n):
    """Return True if n is a power of two."""
    if n <= 0:
        return False
    else:
        return n & (n - 1) == 0
 
 
n = int(input('Enter a number: '))
 
if is_power_of_two(n):
    print('{} is a power of two.'.format(n))
else:
    print('{} is not a power of two.'.format(n))

SyntaxError: invalid syntax (<ipython-input-17-c2598ace6de0>, line 1)

In [18]:
# Program to display the Fibonacci sequence up to n-th term

nterms = int(input("How many terms? "))

# first two terms
n1, n2 = 0, 1
count = 0

# check if the number of terms is valid
if nterms <= 0:
   print("Please enter a positive integer")
elif nterms == 1:
   print("Fibonacci sequence upto",nterms,":")
   print(n1)
else:
   print("Fibonacci sequence:")
   while count < nterms:
       print(n1)
       nth = n1 + n2
       # update values
       n1 = n2
       n2 = nth
       count=count+1

How many terms? 6
Fibonacci sequence:
0
1
1
2
3
5
